name: Build iOS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install buildozer==1.5.0
    
    - name: Build iOS
      run: |
        cd ios
        buildozer ios debug
    
    - uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: ios/bin/*.ipa
